spring:
  application:
    name: api-gateway
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'

zuul:
  sensitiveHeaders: Cookie,Set-Cookie

ribbon:
  eureka:
    enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/microservice-demo-auth
    username: admin
    password: password
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    generate-ddl: true
    show-sql: true