spring:
  application:
    name: api-gateway
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'

zuul:
  sensitiveHeaders: Cookie,Set-Cookie

ribbon:
  eureka:
    enabled: true