spring:
  application:
    name: service1
server:
  port: 8061

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
jwt:
  secret: shushhIamSecret
      
security:
 oauth2:
  resource:
    userInfoUri: http://localhost:8080/authorization-service/user