server:
  port: 8060

spring:
  application:
    name: authorization-service
  datasource:
    url: jdbc:postgresql://localhost:5555/microservice-demo-auth
    username: admin
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: shushhIamSecret
      